data:
    container_name: ci_data
    image: busybox
    volumes:
        - ../:/var/www/ci
        - /vendor
        - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
        - ~/.composer:/root/.composer
        - /tmpfs

nginx:
    container_name: ci_nginx
    image: nginx:1.7
    links:
        - php
    volumes_from:
        - data
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

db:
    container_name: ci_mongo
    image: mongo:3.2

php:
    container_name: ci_php
    build: php
    working_dir: /var/www/ci
    environment:
      CI_ENV: development
    volumes_from:
        - data
    links:
        - db
    mem_limit: 2000000000
